services:

  mysql:
    image: mysql:8
    container_name: izibus_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  springboot-app:
    image: zbestleboss/izibus_backend-ec2
    container_name: izibus_backend-ec2
    restart: always

    env_file:
      - .env

    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - spring-network

  angular-app:
    image: zbestleboss/izibus_frontend-ec2
    container_name: izibus_frontend-ec2
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - springboot-app
    networks:
      - spring-network


networks:
  spring-network:
    driver: bridge

volumes:
  mysql_data: