spring.application.name=izibus
server.port=${PORT:8080}

spring.datasource.url= jdbc:mysql://localhost:3306/izibus
spring.datasource.username=root
spring.datasource.password=z_verseau@1234
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true
logging.level.org.springframework.security=DEBUG


twilio.account-sid=ACxxxxxxxxxxxxxxxxxxxxxxxxxxxx
twilio.auth-token=xxxxxxxxxxxxxxxxxxxxxxxxxxxx
twilio.phone-number=+1234567890

app.secret-key= 5858585888585858747892229419878272992439696971414
app.expirationTime= 3600000


#hibernate config
spring.jpa.hibernate.ddl-auto= update
#spring.main.banner-mode = off


